### ISSUE TITLE
Project 1: Whaddya think?

### ISSUE THREAD

**Issue by bmizepatterson** [bmizepatterson/michael-scott-constable#1]
### Project 1: Michael Scott for Constable

Some things to comment about:

- Color palette
- What is your eye drawn to first?
- Is all text readable?
- Does the layout make sense to you? Anything you'd recommend I reorganize or switch around?

Thanks!

**Comment by JTHall94** [comment]
Wow Ben! This looks really good! I love that you designed it all on one page with links to jump around, rather than designing separate pages! I think the design is really good as well.

One small thing I would consider would be changing the way that the Election Day banner displays upon first loading the page. As it stands, when you load in, it cuts off right beneath the donate heading for the page, and the colors of each sort of conflict. I think maybe just shrinking the size of the banner a little bit might help.

**Comment by Kiwipup** [comment]
It looks awesome Ben! The only thing I noticed that I though maybe could be rearranged a little bit would be the text area that says "Michael Scott for Fayette county constable" and the small text box beneath it. Maybe they could be a little more aligned?? :)
